# Site settings
title: "Shyama Manpower & Licensing Solutions"
description: "Comprehensive workforce recruitment, labour law compliance, and licensing & government liaison services."
url: "https://<your-username>.github.io"
baseurl: "/Shyama-Manpower-Licensing-Solutions"  # Rename if your repo name is different

# Theme and Markdown
theme: minima
markdown: kramdown

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Build settings
paginate: 5
exclude:
  - node_modules
  - vendor
  - README.md

# Front matter defaults (so you don't need to specify layout each time)
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

# Custom site variables
contact_email: "info@shyama-mls.com"
footer_links:
  linkedin: "your-linkedin-profile"
  twitter: "your-twitter-handle"
